=begin comment

Telstra Programmable Network API

Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.1.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package TelstraTPN::Object::Object52;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use TelstraTPN::Object::Classification;
use TelstraTPN::Object::Flavor;
use TelstraTPN::Object::GlanceImage;
use TelstraTPN::Object::Product;
use TelstraTPN::Object::VnfTag;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Telstra Programmable Network API

Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.1.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "TelstraTPN::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'Object52',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'brief_description' => {
    	datatype => 'string',
    	base_name => 'brief_description',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'buyers' => {
    	datatype => 'string',
    	base_name => 'buyers',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'classifications' => {
    	datatype => 'ARRAY[Classification]',
    	base_name => 'classifications',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'comments' => {
    	datatype => 'string',
    	base_name => 'comments',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'create_at' => {
    	datatype => 'int',
    	base_name => 'create_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'creator' => {
    	datatype => 'string',
    	base_name => 'creator',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'description' => {
    	datatype => 'string',
    	base_name => 'description',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'eos' => {
    	datatype => 'string',
    	base_name => 'eos',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'flavors' => {
    	datatype => 'ARRAY[Flavor]',
    	base_name => 'flavors',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'flavors_price' => {
    	datatype => 'string',
    	base_name => 'flavors_price',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'glance_comments' => {
    	datatype => 'string',
    	base_name => 'glance_comments',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'glance_image' => {
    	datatype => 'GlanceImage',
    	base_name => 'glance_image',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'glance_name' => {
    	datatype => 'string',
    	base_name => 'glance_name',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'glance_properties' => {
    	datatype => 'string',
    	base_name => 'glance_properties',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'image_format' => {
    	datatype => 'string',
    	base_name => 'image_format',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'license_required' => {
    	datatype => 'boolean',
    	base_name => 'license_required',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'logo' => {
    	datatype => 'string',
    	base_name => 'logo',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'max_ports' => {
    	datatype => 'int',
    	base_name => 'max_ports',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'md5' => {
    	datatype => 'string',
    	base_name => 'md5',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'min_ports' => {
    	datatype => 'int',
    	base_name => 'min_ports',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'name' => {
    	datatype => 'string',
    	base_name => 'name',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'os_version' => {
    	datatype => 'string',
    	base_name => 'os_version',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'owner' => {
    	datatype => 'string',
    	base_name => 'owner',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'product' => {
    	datatype => 'Product',
    	base_name => 'product',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'publish_date' => {
    	datatype => 'string',
    	base_name => 'publish_date',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'restrict_vnc_console' => {
    	datatype => 'boolean',
    	base_name => 'restrict_vnc_console',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'status' => {
    	datatype => 'string',
    	base_name => 'status',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'support_hot_plug' => {
    	datatype => 'boolean',
    	base_name => 'support_hot_plug',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'tags' => {
    	datatype => 'ARRAY[VnfTag]',
    	base_name => 'tags',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'upload_at' => {
    	datatype => 'int',
    	base_name => 'upload_at',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'vendor_name' => {
    	datatype => 'string',
    	base_name => 'vendor_name',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'zero_day_config_spec' => {
    	datatype => 'string',
    	base_name => 'zero_day_config_spec',
    	description => '',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'brief_description' => 'string',
    'buyers' => 'string',
    'classifications' => 'ARRAY[Classification]',
    'comments' => 'string',
    'create_at' => 'int',
    'creator' => 'string',
    'description' => 'string',
    'eos' => 'string',
    'flavors' => 'ARRAY[Flavor]',
    'flavors_price' => 'string',
    'glance_comments' => 'string',
    'glance_image' => 'GlanceImage',
    'glance_name' => 'string',
    'glance_properties' => 'string',
    'id' => 'int',
    'image_format' => 'string',
    'license_required' => 'boolean',
    'logo' => 'string',
    'max_ports' => 'int',
    'md5' => 'string',
    'min_ports' => 'int',
    'name' => 'string',
    'os_version' => 'string',
    'owner' => 'string',
    'product' => 'Product',
    'publish_date' => 'string',
    'restrict_vnc_console' => 'boolean',
    'status' => 'string',
    'support_hot_plug' => 'boolean',
    'tags' => 'ARRAY[VnfTag]',
    'upload_at' => 'int',
    'vendor_name' => 'string',
    'zero_day_config_spec' => 'string'
} );

__PACKAGE__->attribute_map( {
    'brief_description' => 'brief_description',
    'buyers' => 'buyers',
    'classifications' => 'classifications',
    'comments' => 'comments',
    'create_at' => 'create_at',
    'creator' => 'creator',
    'description' => 'description',
    'eos' => 'eos',
    'flavors' => 'flavors',
    'flavors_price' => 'flavors_price',
    'glance_comments' => 'glance_comments',
    'glance_image' => 'glance_image',
    'glance_name' => 'glance_name',
    'glance_properties' => 'glance_properties',
    'id' => 'id',
    'image_format' => 'image_format',
    'license_required' => 'license_required',
    'logo' => 'logo',
    'max_ports' => 'max_ports',
    'md5' => 'md5',
    'min_ports' => 'min_ports',
    'name' => 'name',
    'os_version' => 'os_version',
    'owner' => 'owner',
    'product' => 'product',
    'publish_date' => 'publish_date',
    'restrict_vnc_console' => 'restrict_vnc_console',
    'status' => 'status',
    'support_hot_plug' => 'support_hot_plug',
    'tags' => 'tags',
    'upload_at' => 'upload_at',
    'vendor_name' => 'vendor_name',
    'zero_day_config_spec' => 'zero_day_config_spec'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
