=begin comment

Telstra Programmable Network API

Telstra Programmable Network is a self-provisioning platform that allows its users to create on-demand connectivity services between multiple end-points and add various network functions to those services. Programmable Network enables to connectivity to a global ecosystem of networking services as well as public and private cloud services. Once you are connected to the platform on one or more POPs (points of presence), you can start creating those services based on the use case that you want to accomplish. The Programmable Network API is available to all customers who have registered to use the Programmable Network. To register, please contact your account representative.

OpenAPI spec version: 2.1.2

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('TelstraTPN::ContractsApi');

my $api = TelstraTPN::ContractsApi->new();
isa_ok($api, 'TelstraTPN::ContractsApi');

#
# create_new_contract_on_specified_link test
#
{
    my $linkid = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $result = $api->create_new_contract_on_specified_link(linkid => $linkid, body => $body);
}

#
# get_active_contract_by_contract_id test
#
{
    my $linkid = undef; # replace NULL with a proper value
    my $contractid = undef; # replace NULL with a proper value
    my $result = $api->get_active_contract_by_contract_id(linkid => $linkid, contractid => $contractid);
}

#
# update_active_contract_by_contract_id test
#
{
    my $linkid = undef; # replace NULL with a proper value
    my $contractid = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $result = $api->update_active_contract_by_contract_id(linkid => $linkid, contractid => $contractid, body => $body);
}


1;
